esphome:
  name: jasper_room_lights
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot
  manual_ip:
    static_ip: 192.168.50.4
    gateway: 192.168.50.1
    subnet: 255.255.255.0

api:
  password: !secret jasper_room_lights_api_password

logger:
  baud_rate: 0
  level: info

ota:
  password: !secret jasper_room_lights_ota_password

uart:
  tx_pin: GPIO01
  rx_pin: GPIO03
  baud_rate: 19200

sensor:
  - platform: uptime
    name: 'jasper_room_lights_uptime'

  - platform: wifi_signal
    name: 'jasper_room_lights_wifi_signal'

switch:
  - platform: uart
    id: relay_12_off
    data: [0xA0, 0x04, 0x00, 0xA1]

  - platform: uart
    id: relay_1_on
    data: [0xA0, 0x04, 0x01, 0xA1]

  - platform: uart
    id: relay_2_on
    data: [0xA0, 0x04, 0x02, 0xA1]

  - platform: uart
    id: relay_12_on
    data: [0xA0, 0x04, 0x03, 0xA1]

  - platform: template
    id: relay1
    name: "jasper_room_lights_relay1"
    turn_on_action:
      if:
        condition:
          switch.is_off: relay2
        then:
          - switch.turn_on: relay_1_on
        else:
          - switch.turn_on: relay_12_on
    turn_off_action:
      if:
        condition:
          switch.is_off: relay2
        then:
          - switch.turn_on: relay_12_off
        else:
          - switch.turn_on: relay_2_on
    optimistic: true

  - platform: template
    id: relay2
    name: "jasper_room_lights_relay2"
    turn_on_action:
      if:
        condition:
          switch.is_off: relay1
        then:
          - switch.turn_on: relay_2_on
        else:
          - switch.turn_on: relay_12_on
    turn_off_action:
      if:
        condition:
          switch.is_off: relay1
        then:
          - switch.turn_on: relay_12_off
        else:
          - switch.turn_on: relay_1_on
    optimistic: true
