esphome:
  name: jasper-room-multisensor
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot
  manual_ip:
    static_ip: 192.168.50.2
    gateway: 192.168.50.1
    subnet: 255.255.255.0

api:
  # reboot_timeout: 0s
  encryption:
    key: !secret jasper_room_multisensor_api_encryption_key

logger:
  level: info

ota:
  password: !secret jasper_room_multisensor_ota_password

binary_sensor:
  - platform: gpio
    pin: D5
    name: jasper_room_multisensor_pir

sensor:
  - platform: dht
    pin: D3
    model: DHT11
    temperature:
      filters:
        offset: -5.0
      name: jasper_room_multisensor_temperature
    humidity:
      filters:
      name: jasper_room_multisensor_humidity
    update_interval: 10s

  - platform: uptime
    name: jasper_room_multisensor_uptime

  - platform: wifi_signal
    name: jasper_room_multisensor_wifi_signal
