esphomeyaml:
  name: jasper_zimmer_multisensor
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot

api:
  

# Enable logging
logger:
  level: info

ota:
  password: !secret jasper_zimmer_multisensor_ota_password

binary_sensor:
  - platform: gpio
    pin: D5
    name: 'jasper_zimmer_multisensor_pir'

sensor:
  - platform: dht
    pin: D4
    model: DHT11
    temperature:
      filters:
        offset: -5.0
      name: 'jasper_zimmer_multisensor_temperature'
    humidity:
      filters:
      name: 'jasper_zimmer_multisensor_humidity'
    update_interval: 10s

  - platform: uptime
    name: 'jasper_zimmer_multisensor_uptime'

  - platform: wifi_signal
    name: 'jasper_zimmer_multisensor_wifi_signal'
    update_interval: 10s
