esphome:
  name: outlet-6
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot
  manual_ip:
    static_ip: 192.168.50.12
    gateway: 192.168.50.1
    subnet: 255.255.255.0

logger:
  level: info

api:
  # reboot_timeout: 0s
  encryption:
    key: !secret outlet_6_api_encryption_key

ota:
  password: !secret outlet_6_ota_password

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 192.168.50.1

sensor:
  - platform: uptime
    name: outlet_6_uptime

  - platform: wifi_signal
    name: outlet_6_wifi_signal

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO04
    change_mode_every: 3
    update_interval: 3s
    current:
      name: outlet_6_current
      filters:
        - calibrate_linear:
            - 0.025 -> 0.000
            - 0.21727 -> 0.17
            - 2.250 -> 1.840
        - lambda: |
            if (x < 0) return 0; 
            else return x;
    voltage:
      name: outlet_6_voltage
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 707.75842 -> 223.0
            - 714.84149 -> 224.0
        - lambda: |
            if (x < 0) return 0; 
            else return x;
    power:
      name: outlet_6_power
      id: outlet_6_power
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 289.62112 -> 38.0
            - 293.06903 -> 39.0
            - 3061.70898 -> 412.0
            - 3068.60474 -> 413.0
            - 3075.50073 -> 414.0
        - lambda: |
            if (x < 0) return 0; 
            else return x;

  - platform: total_daily_energy
    name: outlet_6_daily_energy
    power_id: outlet_6_power

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay
    internal: True

switch:
  - platform: gpio
    id: relay
    name: outlet_6_relay
    pin: GPIO15
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led

  - platform: gpio
    id: blue_led
    pin:
      number: GPIO02
      inverted: True

status_led:
  pin:
    number: GPIO00
    inverted: True
