esphome:
  name: outlet-2
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot
  manual_ip:
    static_ip: 192.168.50.8
    gateway: 192.168.50.1
    subnet: 255.255.255.0

logger:
  level: info

api:
  # reboot_timeout: 0s
  encryption:
    key: !secret outlet_2_api_encryption_key

ota:
  password: !secret outlet_2_ota_password

sensor:
  - platform: uptime
    name: 'outlet_2_uptime'

  - platform: wifi_signal
    name: 'outlet_2_wifi_signal'

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    change_mode_every: 3
    update_interval: 3s
    current:
      name: "outlet_2_current"
      filters:
      - calibrate_linear:
          - 0.11153 -> 0.0
          - 0.42295 -> 0.17
          - 2.56086 -> 1.86
    voltage:
      name: "outlet_2_voltage"
      filters:
      - calibrate_linear:
          - 596.32324 -> 223.0
          - 597.22229 -> 224.0
          - 597.75348 -> 225.0
    power:
      name: "outlet_2_power"
      filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 264.79648 -> 40.0
          - 2792.77515 -> 418.0

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay
    internal: True

switch:
  - platform: gpio
    id: relay
    name: outlet_2_relay
    pin: GPIO15
    on_turn_on:
    - switch.turn_on: blue_led
    on_turn_off:
    - switch.turn_off: blue_led

  - platform: gpio
    id: blue_led
    pin:
      number: GPIO02
      inverted: True

status_led:
  pin:
    number: GPIO00
    inverted: True
