esphome:
  name: outlet_3
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot
  manual_ip:
    static_ip: 192.168.50.9
    gateway: 192.168.50.1
    subnet: 255.255.255.0

# Enable logging
logger:
  # level: debug
  level: info

# Enable Home Assistant API
api:
  password: !secret outlet_3_api_password

ota:
  password: !secret outlet_3_ota_password

sensor:
  - platform: uptime
    name: 'outlet_3_uptime'

  - platform: wifi_signal
    name: 'outlet_3_wifi_signal'

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    change_mode_every: 3
    update_interval: 3s
    current:
      name: "outlet_3_current"
      filters:
      - calibrate_linear:
          - 0.11105 -> 0.0
          - 0.36646 -> 0.17
          - 0.34763 -> 0.18
          - 2.58838 -> 1.86
          - 2.61445 -> 1.87
    voltage:
      name: "outlet_3_voltage"
      filters:
      - calibrate_linear:
          - 609.93079 -> 224.0
          - 614.50757 -> 225.0
    power:
      name: "outlet_3_power"
      filters:
      - calibrate_linear:
        - 0.00000 -> 0.0
        - 265.83084 -> 40.0
        - 2872.42114 -> 418.0
        - 2875.52417 -> 419.01

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay
    internal: True

switch:
  - platform: gpio
    id: relay
    name: outlet_3_relay
    pin: GPIO15
    on_turn_on:
    - switch.turn_on: blue_led
    on_turn_off:
    - switch.turn_off: blue_led

  - platform: gpio
    id: blue_led
    pin:
      number: GPIO02
      inverted: True

status_led:
  pin:
    number: GPIO00
    inverted: True
