esphome:
  name: outlet-1
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot
  manual_ip:
    static_ip: 192.168.50.5
    gateway: 192.168.50.1
    subnet: 255.255.255.0

logger:
  level: info

api:
  # reboot_timeout: 0s
  encryption:
    key: !secret outlet_1_api_encryption_key

ota:
  password: !secret outlet_1_ota_password

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 192.168.50.1

sensor:
  - platform: uptime
    name: outlet_1_uptime

  - platform: wifi_signal
    name: outlet_1_wifi_signal

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current_resistor: 0.00125
    voltage_divider: 874
    update_interval: 10s
    current:
      name: outlet_1_current
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 1.8 -> 1.83
        - lambda: |
            if (x < 0) return 0; 
            else return x;

    voltage:
      name: outlet_1_voltage
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 221.0 -> 220.0
        - lambda: |
            if (x < 0) return 0; 
            else return x;

    power:
      name: outlet_1_power
      id: outlet_1_power
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 724.0 -> 404.0
        - lambda: |
            if (x < 0) return 0; 
            else return x;

  - platform: total_daily_energy
    name: outlet_1_daily_energy
    power_id: outlet_1_power

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay
    internal: True

switch:
  - platform: gpio
    id: relay
    name: outlet_1_relay
    pin: GPIO14
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led

  - platform: gpio
    id: blue_led
    pin:
      number: GPIO01
      inverted: True

status_led:
  pin:
    number: GPIO13
    inverted: True
