esphome:
  name: outlet-7
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot
  manual_ip:
    static_ip: 192.168.50.13
    gateway: 192.168.50.1
    subnet: 255.255.255.0

logger:
  level: info

api:
  # reboot_timeout: 0s
  encryption:
    key: !secret outlet_7_api_encryption_key

ota:
  password: !secret outlet_7_ota_password

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 192.168.50.1

sensor:
  - platform: uptime
    name: outlet_7_uptime

  - platform: wifi_signal
    name: outlet_7_wifi_signal

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO04
    change_mode_every: 3
    update_interval: 3s
    current:
      name: outlet_7_current
      filters:
        - calibrate_linear:
            - 0.01931 -> 0.000
            - 0.21244 -> 0.17
            - 2.19199 -> 1.83
            - 2.20164 -> 1.84
        - lambda: |
            if (x < 0) return 0; 
            else return x;
    voltage:
      name: outlet_7_voltage
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 699.72192 -> 222.0
            - 702.58240 -> 223.0
        - lambda: |
            if (x < 0) return 0; 
            else return x;
    power:
      name: outlet_7_power
      id: outlet_7_power
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 286.17325 -> 38.0
            - 2989.30371 -> 410.0
            - 3006.54321 -> 411.0
        - lambda: |
            if (x < 0) return 0; 
            else return x;

  - platform: total_daily_energy
    name: outlet_7_daily_energy
    power_id: outlet_7_power

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay
    internal: True

switch:
  - platform: gpio
    id: relay
    name: outlet_7_relay
    pin: GPIO15
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led

  - platform: gpio
    id: blue_led
    pin:
      number: GPIO02
      inverted: True

status_led:
  pin:
    number: GPIO00
    inverted: True
