esphome:
  name: outlet-4
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot
  manual_ip:
    static_ip: 192.168.50.10
    gateway: 192.168.50.1
    subnet: 255.255.255.0

logger:
  level: info

api:
  # reboot_timeout: 0s
  encryption:
    key: !secret outlet_4_api_encryption_key

ota:
  password: !secret outlet_4_ota_password

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 192.168.50.1

sensor:
  - platform: uptime
    name: outlet_4_uptime

  - platform: wifi_signal
    name: outlet_4_wifi_signal

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    change_mode_every: 3
    update_interval: 3s
    current:
      name: outlet_4_current
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 0.28969 -> 0.17
            - 0.30128 -> 0.18
            - 2.56376 -> 1.86
    voltage:
      name: outlet_4_voltage
      filters:
        - calibrate_linear:
            - 586.25714 -> 222.0
            - 583.94159 -> 223.0
            - 591.13354 -> 224.0
            - 593.61261 -> 225.0

    power:
      name: outlet_4_power
      id: outlet_4_power
      filters:
        - calibrate_linear:
            - 13.79148 -> 0.0
            - 265.48602 -> 40.0
            - 2837.59766 -> 415.0
            - 2841.04517 -> 416.0

  - platform: total_daily_energy
    name: outlet_4_daily_energy
    power_id: outlet_4_power

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay
    internal: True

switch:
  - platform: gpio
    id: relay
    name: outlet_4_relay
    pin: GPIO15
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led

  - platform: gpio
    id: blue_led
    pin:
      number: GPIO02
      inverted: True

status_led:
  pin:
    number: GPIO00
    inverted: True
