esphome:
  name: outlet-3

esp8266:
  board: esp01_1m
  board_flash_mode: dout
  restore_from_flash: true

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot
  manual_ip:
    static_ip: 192.168.50.9
    gateway: 192.168.50.1
    subnet: 255.255.255.0

logger:
  level: info

api:
  # reboot_timeout: 0s
  encryption:
    key: !secret outlet_3_api_encryption_key

ota:
  password: !secret outlet_3_ota_password

time:
  - platform: sntp
    id: sntp_time
    servers:
      - 192.168.50.1

sensor:
  - platform: uptime
    name: outlet_3_uptime

  - platform: wifi_signal
    name: outlet_3_wifi_signal

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO14
    change_mode_every: 3
    update_interval: 3s
    current:
      name: outlet_3_current
      filters:
        - calibrate_linear:
            - 0.11105 -> 0.0
            - 0.36646 -> 0.17
            - 0.34763 -> 0.18
            - 2.58838 -> 1.86
            - 2.61445 -> 1.87
        - lambda: |
            if (x < 0) return 0; 
            else return x;
    voltage:
      name: outlet_3_voltage
      filters:
        - calibrate_linear:
            - 609.93079 -> 224.0
            - 614.50757 -> 225.0
        - lambda: |
            if (x < 0) return 0; 
            else return x;

    power:
      name: outlet_3_power
      id: outlet_3_power
      filters:
        - calibrate_linear:
            - 0.00000 -> 0.0
            - 265.83084 -> 40.0
            - 2872.42114 -> 418.0
            - 2875.52417 -> 419.01
        - lambda: |
            if (x < 0) return 0; 
            else return x;

  - platform: total_daily_energy
    name: outlet_3_daily_energy
    power_id: outlet_3_power

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay
    internal: True

switch:
  - platform: gpio
    id: relay
    name: outlet_3_relay
    pin: GPIO15
    on_turn_on:
      - switch.turn_on: blue_led
    on_turn_off:
      - switch.turn_off: blue_led
    restore_mode: RESTORE_DEFAULT_ON

  - platform: gpio
    id: blue_led
    pin:
      number: GPIO02
      inverted: True
    restore_mode: RESTORE_DEFAULT_ON

status_led:
  pin:
    number: GPIO00
    inverted: True
