esphome:
  name: outlet_7
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot
  manual_ip:
    static_ip: 192.168.50.13
    gateway: 192.168.50.1
    subnet: 255.255.255.0

logger:
  level: info

api:
  password: !secret outlet_7_api_password
  reboot_timeout: 0s

ota:
  password: !secret outlet_7_ota_password

sensor:
  - platform: uptime
    name: 'outlet_7_uptime'

  - platform: wifi_signal
    name: 'outlet_7_wifi_signal'

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO05
    cf1_pin: GPIO04
    change_mode_every: 3
    update_interval: 3s
    current:
      name: "outlet_6_current"
      filters:
      - calibrate_linear:
          - 0.01931 -> 0.000
          - 0.21244 -> 0.17
          - 2.19199 -> 1.83
          - 2.20164 -> 1.84
    voltage:
      name: "outlet_6_voltage"
      filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 699.72192 -> 222.0
          - 702.58240 -> 223.0
    power:
      name: "outlet_6_power"
      filters:
      - calibrate_linear:
          - 0.0 -> 0.0
          - 286.17325 -> 38.0
          - 2989.30371 -> 410.0
          - 3006.54321 -> 411.0

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: relay
    internal: True

switch:
  - platform: gpio
    id: relay
    name: outlet_7_relay
    pin: GPIO15
    on_turn_on:
    - switch.turn_on: blue_led
    on_turn_off:
    - switch.turn_off: blue_led

  - platform: gpio
    id: blue_led
    pin:
      number: GPIO02
      inverted: True

status_led:
  pin:
    number: GPIO00
    inverted: True
