esphome:
  name: test_nodemcu
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot
  manual_ip:
    static_ip: 192.168.50.3
    gateway: 192.168.50.1
    subnet: 255.255.255.0

api:
  password: !secret test_nodemcu_api_password

ota:
  password: !secret test_nodemcu_ota_password
  
# Enable logging
logger:
  baud_rate: 0

uart:
  tx_pin: GPIO01
  rx_pin: GPIO03
  baud_rate: 19200

sensor:
  - platform: uptime
    name: 'test_nodemcu_uptime'
  
  - platform: wifi_signal
    name: 'test_nodemcu_wifi_signal'

switch:
  - platform: uart
    id: relay_12_off
    data: [0xA0, 0x04, 0x00, 0xA1]
    
  - platform: uart
    id: relay_1_on
    data: [0xA0, 0x04, 0x01, 0xA1]
    
  - platform: uart
    id: relay_2_on
    data: [0xA0, 0x04, 0x02, 0xA1]
    
  - platform: uart
    id: relay_12_on
    data: [0xA0, 0x04, 0x03, 0xA1]

  - platform: template
    id: relay1
    name: "test_nodemcu_lights_relay1"
    turn_on_action:
      if:
        condition:
          switch.is_off: relay2
        then:
          - switch.turn_on: relay_1_on
        else:
          - switch.turn_on: relay_12_on
    turn_off_action:
      if:
        condition:
          switch.is_off: relay2
        then:
          - switch.turn_on: relay_12_off
        else:
          - switch.turn_on: relay_2_on
    optimistic: true
        
  - platform: template
    id: relay2
    name: "test_nodemcu_lights_relay2"
    turn_on_action:
      if:
        condition:
          switch.is_off: relay1
        then:
          - switch.turn_on: relay_2_on
        else:
          - switch.turn_on: relay_12_on
    turn_off_action:
      if:
        condition:
          switch.is_off: relay1
        then:
          - switch.turn_on: relay_12_off
        else:
          - switch.turn_on: relay_1_on
    optimistic: true

web_server:
  port: 80