esphome:
  name: test_nodemcu
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot
  manual_ip:
    static_ip: 192.168.50.3
    gateway: 192.168.50.1
    subnet: 255.255.255.0

api:
  password: !secret test_nodemcu_api_password

logger:
  level: info

ota:
  password: !secret test_nodemcu_ota_password

binary_sensor:
  - platform: gpio
    pin: D5
    name: 'test_nodemcu_pir'

sensor:
  - platform: uptime
    name: 'test_nodemcu_uptime'

  - platform: wifi_signal
    name: 'test_nodemcu_wifi_signal'