esphome:
  name: test_nodemcu
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot
  manual_ip:
    static_ip: 192.168.50.3
    gateway: 192.168.50.1
    subnet: 255.255.255.0

api:
  password: !secret test_nodemcu_api_password

logger:
  level: debug

ota:
  password: !secret test_nodemcu_ota_password

sensor:
- platform: ntc
  name: test_nodemcu_temperature
  sensor: resistance_sensor
  calibration:
    # b_constant: 3950
    # reference_temperature: 25째C
    # reference_resistance: 100kOhm
    - 100.366kOhm -> 23.4째C
    - 63.307kOhm -> 34.8째C
    - 304.502kOhm -> -6.1째C
- platform: resistance
  id: resistance_sensor
  sensor: source_sensor
  configuration: DOWNSTREAM
  resistor: 32.59kOhm
  reference_voltage: 1.0V
- platform: adc
  id: source_sensor
  pin: A0
  update_interval: never
- platform: uptime
  name: 'test_nodemcu_uptime'

switch:
- platform: gpio
  pin: D1
  id: ntc_vcc

interval:
- interval: 60s
  then:
  - switch.turn_on: ntc_vcc
  - component.update: source_sensor
  - switch.turn_off: ntc_vcc
