esphomeyaml:
  name: test_nodemcu
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wlan_ssid
  password: !secret wlan_password
  domain: .iot

api:

# Enable logging
logger:
  level: info

ota:
  password: !secret test_nodemcu_ota_password

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
    name: 'test_nodemcu_switch1'

output:
  - platform: esp8266_pwm
    pin: D0
    id: gpio_r
  - platform: esp8266_pwm
    pin: D1
    id: gpio_g
  - platform: esp8266_pwm
    pin: D6
    id: gpio_b

light:
  - platform: rgb
    name: 'test_nodemcu_rgb1'
    red: gpio_r
    green: gpio_g
    blue: gpio_b
